//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace quiz.entities
{
    public partial class QuizContext : ObjectContext
    {
        public const string ConnectionString = "name=quizContainer";
        public const string ContainerName = "quizContainer";
    
        #region Constructors
    
        public QuizContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public QuizContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public QuizContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<Quiz> Quizs
        {
            get { return _quizs  ?? (_quizs = CreateObjectSet<Quiz>("Quizs")); }
        }
        private ObjectSet<Quiz> _quizs;
    
        public ObjectSet<Question> Questions
        {
            get { return _questions  ?? (_questions = CreateObjectSet<Question>("Questions")); }
        }
        private ObjectSet<Question> _questions;
    
        public ObjectSet<Answer> Answers
        {
            get { return _answers  ?? (_answers = CreateObjectSet<Answer>("Answers")); }
        }
        private ObjectSet<Answer> _answers;
    
        public ObjectSet<Stat> Stats
        {
            get { return _stats  ?? (_stats = CreateObjectSet<Stat>("Stats")); }
        }
        private ObjectSet<Stat> _stats;

        #endregion
    }
}
