//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace quiz.entities
{
    /// <summary>
    /// Class <see cref="Stat "/> 
    /// </summary>
    public partial class Stat
    {
        #region Primitive Properties
        /// <summary>
        /// Stat identifier
        /// </summary>
        public virtual int StatId
        {
            get;
            set;
        }
        /// <summary>
        /// User identifier
        /// </summary>
        public virtual int Users_UserId
        {
            get { return _users_UserId; }
            set
            {
                if (_users_UserId != value)
                {
                    if (User != null && User.UserId != value)
                    {
                        User = null;
                    }
                    _users_UserId = value;
                }
            }
        }
        private int _users_UserId;
        /// <summary>
        /// Quiz identifier
        /// </summary>
        public virtual int Quizs_QuizId
        {
            get { return _quizs_QuizId; }
            set
            {
                if (_quizs_QuizId != value)
                {
                    if (Quiz != null && Quiz.QuizId != value)
                    {
                        Quiz = null;
                    }
                    _quizs_QuizId = value;
                }
            }
        }
        private int _quizs_QuizId;
        /// <summary>
        /// Count of correct answers
        /// </summary>
        public virtual int CorrectAnswers
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Quiz Quiz
        {
            get { return _quiz; }
            set
            {
                if (!ReferenceEquals(_quiz, value))
                {
                    var previousValue = _quiz;
                    _quiz = value;
                    FixupQuiz(previousValue);
                }
            }
        }
        private Quiz _quiz;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupQuiz(Quiz previousValue)
        {
            if (previousValue != null && previousValue.Stats.Contains(this))
            {
                previousValue.Stats.Remove(this);
            }
    
            if (Quiz != null)
            {
                if (!Quiz.Stats.Contains(this))
                {
                    Quiz.Stats.Add(this);
                }
                if (Quizs_QuizId != Quiz.QuizId)
                {
                    Quizs_QuizId = Quiz.QuizId;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Stats.Contains(this))
            {
                previousValue.Stats.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Stats.Contains(this))
                {
                    User.Stats.Add(this);
                }
                if (Users_UserId != User.UserId)
                {
                    Users_UserId = User.UserId;
                }
            }
        }

        #endregion
    }
}
